#!/usr/bin/env node

const { exec } = require('child_process');
console.log('Checking for coverage');
exec('npm run test:coverage', (error, stdout, stderr) => {
  if (error) {
    console.log(`error: ${error.message}`);
    return;
  }
  if (stderr) {
    console.log(`stderr: ${stderr}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
});
console.log('Coverage test passed, pushing branch...');
