#!/usr/bin/env node

//commit message endswith 1234
console.log(process.argv);
const fs = require('fs');
const message = fs.readFileSync(process.argv[2], 'utf8').trim();
console.log(message);
const newMessage = `${message} ${Date.now().toString()}`;
fs.writeFileSync(process.argv[2], newMessage);
// if (message.endsWith('1234')) {
//   console.log('Commit-msg hook passed, commiting....');
//   process.exit(0);
// }
// console.log('rejecting commit');
// process.exit(1);
