#!/usr/bin/env node

const { exec } = require('child_process');
console.log('Checking for coverage');
exec('npm run lint', (error, stdout, stderr) => {
  if (error || stderr) {
    console.log(`Error: ${error.message}`);
    console.log(` stderror: ${stderr.message}`);
    console.log('Coverage test check failed, rejecting push...');
    process.exit(1);
  }
  console.log(`Success: ${stdout}`);
  console.log('Coverage test passed, pushing branch...');
  process.exit(0);
});
